spring.application.name=compliance
spring.cloud.openfeign.client.config.sanction-client.url=http://192.168.64.1:3001
spring.cloud.openfeign.client.config.sanction-client.logger-level=full
spring.cloud.openfeign.client.config.sanction-client.default-request-headers.x-api-key=kyc-secret-123
spring.cloud.openfeign.circuitbreaker.enabled=true
spring.cloud.openfeign.client.config.aml-client.url=http://192.168.64.1:3002
spring.cloud.openfeign.client.config.aml-client.logger-level=full
spring.cloud.openfeign.client.config.aml-client.default-request-headers.authorization=Bearer xyz123
logging.level.dio.compliance.infrastructure.rest=DEBUG
