spring.application.name=marketplace
management.endpoint.health.show-details=always
spring.docker.compose.lifecycle-management=start-only
spring.threads.virtual.enabled=true
spring.data.redis.client-type=jedis
# Registration (MySQL 3307)
registration.datasource.url=jdbc:mysql://localhost:3307/registration
registration.datasource.username=app
registration.datasource.password=app
registration.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
registration.jpa.properties.hibernate.hbm2ddl.auto=update
# Catalog (MySQL 3308)
catalog.datasource.url=jdbc:mysql://localhost:3308/catalog
catalog.datasource.username=app
catalog.datasource.password=app
catalog.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
catalog.jpa.properties.hibernate.hbm2ddl.auto=update
spring.mongodb.representation.uuid=standard
catalog.redis.host=localhost
catalog.redis.port=6380
# Ticketing (Postgres 5433)
ticketing.datasource.url=jdbc:postgresql://localhost:5433/ticketing
ticketing.datasource.username=app
ticketing.datasource.password=app
ticketing.datasource.driver-class-name=org.postgresql.Driver
ticketing.jpa.properties.hibernate.hbm2ddl.auto=update
ticketing.redis.host=localhost
ticketing.redis.port=6381
